"""
    This file holds constants for various country-related information
    To load these constants, import them as usual, e.g.
    
    from ross.core.countries import COUNTRIES
"""

COUNTRIES = (
    ('AF', u'Afghanistan'),
    ('AX', u'\xc5land Islands'),
    ('AL', u'Albania'),
    ('DZ', u'Algeria'),
    ('AS', u'American Samoa'),
    ('AD', u'Andorra'),
    ('AO', u'Angola'),
    ('AI', u'Anguilla'),
    ('AQ', u'Antarctica'),
    ('AG', u'Antigua and Barbuda'),
    ('AR', u'Argentina'),
    ('AM', u'Armenia'),
    ('AW', u'Aruba'),
    ('AU', u'Australia'),
    ('AT', u'Austria'),
    ('AZ', u'Azerbaijan'),
    ('BS', u'Bahamas'),
    ('BH', u'Bahrain'),
    ('BD', u'Bangladesh'),
    ('BB', u'Barbados'),
    ('BY', u'Belarus'),
    ('BE', u'Belgium'),
    ('BZ', u'Belize'),
    ('BJ', u'Benin'),
    ('BM', u'Bermuda'),
    ('BT', u'Bhutan'),
    ('BO', u'Bolivia'),
    ('BQ', u'Bonaire'),
    ('BA', u'Bosnia and Herzegovina'),
    ('BW', u'Botswana'),
    ('BV', u'Bouvet Island'),
    ('BR', u'Brazil'),
    ('IO', u'British Indian Ocean Territory'),
    ('BN', u'Brunei Darussalam'),
    ('BG', u'Bulgaria'),
    ('BF', u'Burkina Faso'),
    ('BI', u'Burundi'),
    ('KH', u'Cambodia'),
    ('CM', u'Cameroon'),
    ('CA', u'Canada'),
    ('CV', u'Cape Verde'),
    ('KY', u'Cayman Islands'),
    ('CF', u'Central African Republic'),
    ('TD', u'Chad'),
    ('CL', u'Chile'),
    ('CN', u'China'),
    ('CX', u'Christmas Island'),
    ('CC', u'Cocos (Keeling) Islands'),
    ('CO', u'Colombia'),
    ('KM', u'Comoros'),
    ('CG', u'Congo'),
    ('CD', u'Congo, The Democratic Republic of the'),
    ('CK', u'Cook Islands'),
    ('CR', u'Costa Rica'),
    ('CI', u"C\xf4te D'ivoire"),
    ('HR', u'Croatia'),
    ('CU', u'Cuba'),
    ('CW', u'Cura\xe7ao'),
    ('CY', u'Cyprus'),
    ('CZ', u'Czech Republic'),
    ('DK', u'Denmark'),
    ('DJ', u'Djibouti'),
    ('DM', u'Dominica'),
    ('DO', u'Dominican Republic'),
    ('EC', u'Ecuador'),
    ('EG', u'Egypt'),
    ('SV', u'El Salvador'),
    ('GQ', u'Equatorial Guinea'),
    ('ER', u'Eritrea'),
    ('EE', u'Estonia'),
    ('ET', u'Ethiopia'),
    ('FK', u'Falkland Islands (Malvinas)'),
    ('FO', u'Faroe Islands'),
    ('FJ', u'Fiji'),
    ('FI', u'Finland'),
    ('FR', u'France'),
    ('GF', u'French Guiana'),
    ('PF', u'French Polynesia'),
    ('TF', u'French Southern Territories'),
    ('GA', u'Gabon'),
    ('GM', u'Gambia'),
    ('GE', u'Georgia'),
    ('DE', u'Germany'),
    ('GH', u'Ghana'),
    ('GI', u'Gibraltar'),
    ('GR', u'Greece'),
    ('GL', u'Greenland'),
    ('GD', u'Grenada'),
    ('GP', u'Guadeloupe'),
    ('GU', u'Guam'),
    ('GT', u'Guatemala'),
    ('GG', u'Guernsey'),
    ('GN', u'Guinea'),
    ('GW', u'Guinea-bissau'),
    ('GY', u'Guyana'),
    ('HT', u'Haiti'),
    ('HM', u'Heard Island and McDonald Islands'),
    ('VA', u'Holy See (Vatican City State)'),
    ('HN', u'Honduras'),
    ('HK', u'Hong Kong'),
    ('HU', u'Hungary'),
    ('IS', u'Iceland'),
    ('IN', u'India'),
    ('ID', u'Indonesia'),
    ('IR', u'Iran'),
    ('IQ', u'Iraq'),
    ('IE', u'Ireland'),
    ('IM', u'Isle of Man'),
    ('IL', u'Israel'),
    ('IT', u'Italy'),
    ('JM', u'Jamaica'),
    ('JP', u'Japan'),
    ('JE', u'Jersey'),
    ('JO', u'Jordan'),
    ('KZ', u'Kazakhstan'),
    ('KE', u'Kenya'),
    ('KI', u'Kiribati'),
    ('KP', u"Korea, Democratic People's Republic of"),
    ('KR', u'Korea, Republic of'),
    ('KW', u'Kuwait'),
    ('KG', u'Kyrgyzstan'),
    ('LA', u"Lao People's Democratic Republic"),
    ('LV', u'Latvia'),
    ('LB', u'Lebanon'),
    ('LS', u'Lesotho'),
    ('LR', u'Liberia'),
    ('LY', u'Libya'),
    ('LI', u'Liechtenstein'),
    ('LT', u'Lithuania'),
    ('LU', u'Luxembourg'),
    ('MO', u'Macao'),
    ('MK', u'Macedonia'),
    ('MG', u'Madagascar'),
    ('MW', u'Malawi'),
    ('MY', u'Malaysia'),
    ('MV', u'Maldives'),
    ('ML', u'Mali'),
    ('MT', u'Malta'),
    ('MH', u'Marshall Islands'),
    ('MQ', u'Martinique'),
    ('MR', u'Mauritania'),
    ('MU', u'Mauritius'),
    ('YT', u'Mayotte'),
    ('MX', u'Mexico'),
    ('FM', u'Micronesia'),
    ('MD', u'Moldova'),
    ('MC', u'Monaco'),
    ('MN', u'Mongolia'),
    ('ME', u'Montenegro'),
    ('MS', u'Montserrat'),
    ('MA', u'Morocco'),
    ('MZ', u'Mozambique'),
    ('MM', u'Myanmar'),
    ('NA', u'Namibia'),
    ('NR', u'Nauru'),
    ('NP', u'Nepal'),
    ('NL', u'Netherlands'),
    ('NC', u'New Caledonia'),
    ('NZ', u'New Zealand'),
    ('NI', u'Nicaragua'),
    ('NE', u'Niger'),
    ('NG', u'Nigeria'),
    ('NU', u'Niue'),
    ('NF', u'Norfolk Island'),
    ('MP', u'Northern Mariana Islands'),
    ('NO', u'Norway'),
    ('OM', u'Oman'),
    ('PK', u'Pakistan'),
    ('PW', u'Palau'),
    ('PS', u'Palestinian Territory, Occupied'),
    ('PA', u'Panama'),
    ('PG', u'Papua New Guinea'),
    ('PY', u'Paraguay'),
    ('PE', u'Peru'),
    ('PH', u'Philippines'),
    ('PN', u'Pitcairn'),
    ('PL', u'Poland'),
    ('PT', u'Portugal'),
    ('PR', u'Puerto Rico'),
    ('QA', u'Qatar'),
    ('RE', u'R\xe9union'),
    ('RO', u'Romania'),
    ('RU', u'Russian Federation'),
    ('RW', u'Rwanda'),
    ('BL', u'Saint Barth\xe9lemy'),
    ('SH', u'Saint Helena, Ascension and Tristan Da Cunha'),
    ('KN', u'Saint Kitts and Nevis'),
    ('LC', u'Saint Lucia'),
    ('MF', u'Saint Martin (French Part)'),
    ('PM', u'Saint Pierre and Miquelon'),
    ('VC', u'Saint Vincent and the Grenadines'),
    ('WS', u'Samoa'),
    ('SM', u'San Marino'),
    ('ST', u'Sao Tome and Principe'),
    ('SA', u'Saudi Arabia'),
    ('SN', u'Senegal'),
    ('RS', u'Serbia'),
    ('SC', u'Seychelles'),
    ('SL', u'Sierra Leone'),
    ('SG', u'Singapore'),
    ('SX', u'Sint Maarten (Dutch Part)'),
    ('SK', u'Slovakia'),
    ('SI', u'Slovenia'),
    ('SB', u'Solomon Islands'),
    ('SO', u'Somalia'),
    ('ZA', u'South Africa'),
    ('GS', u'South Georgia and the South Sandwich Islands'),
    ('SS', u'South Sudan'),
    ('ES', u'Spain'),
    ('LK', u'Sri Lanka'),
    ('SD', u'Sudan'),
    ('SR', u'Suriname'),
    ('SJ', u'Svalbard and Jan Mayen'),
    ('SZ', u'Swaziland'),
    ('SE', u'Sweden'),
    ('CH', u'Switzerland'),
    ('SY', u'Syrian Arab Republic'),
    ('TW', u'Taiwan'),
    ('TJ', u'Tajikistan'),
    ('TZ', u'Tanzania'),
    ('TH', u'Thailand'),
    ('TL', u'Timor-leste'),
    ('TG', u'Togo'),
    ('TK', u'Tokelau'),
    ('TO', u'Tonga'),
    ('TT', u'Trinidad and Tobago'),
    ('TN', u'Tunisia'),
    ('TR', u'Turkey'),
    ('TM', u'Turkmenistan'),
    ('TC', u'Turks and Caicos Islands'),
    ('TV', u'Tuvalu'),
    ('UG', u'Uganda'),
    ('UA', u'Ukraine'),
    ('AE', u'United Arab Emirates'),
    ('GB', u'United Kingdom'),
    ('US', u'United States'),
    ('UM', u'United States Minor Outlying Islands'),
    ('UY', u'Uruguay'),
    ('UZ', u'Uzbekistan'),
    ('VU', u'Vanuatu'),
    ('VE', u'Venezuela'),
    ('VN', u'Viet Nam'),
    ('VG', u'Virgin Islands, British'),
    ('VI', u'Virgin Islands, U.S.'),
    ('WF', u'Wallis and Futuna'),
    ('EH', u'Western Sahara'),
    ('YE', u'Yemen'),
    ('ZM', u'Zambia'),
    ('ZW', u'Zimbabwe'),
)

NATIONALITY = (
    ('AD', u'Andorian'),
    ('AE', u'Emirian'),
    ('AF', u'Afghani'),
    ('AI', u'Anguillan'),
    ('AM', u'Armenian'),
    ('AO', u'Angolian'),
    ('AQ', u'Antarctic'),
    ('AR', u'Argentine'),
    ('AS', u'Austrian'),
    ('AU', u'Australian'),
    ('AW', u'Arubian'),
    ('BA', u'Bangladeshi'),
    ('BB', u'Barbadian'),
    ('BE', u'Belgian'),
    ('BH', u'Bahrainian'),
    ('BM', u'Bermuda'),
    ('BO', u'Bolivian'),
    ('BR', u'Brazilian'),
    ('BS', u'Bahameese'),
    ('BT', u'Bhutanese'),
    ('BU', u'Bulgarian'),
    ('BY', u'Belarusian'),
    ('BZ', u'Belizean'),
    ('CA', u'Canadian'),
    ('CG', u'Congolese'),
    ('CH', u'Chinese'),
    ('CH', u'Swiss'),
    ('CL', u'Chilean'),
    ('CM', u'Cambodian'),
    ('CM', u'Cameroonian'),
    ('CO', u'Columbian'),
    ('CR', u'Czech'),
    ('CR', u'Rican'),
    ('CU', u'Cuban'),
    ('CY', u'Cypriot'),
    ('DE', u'German'),
    ('DK', u'Danish'),
    ('DM', u'Dominican'),
    ('EC', u'Ecuadorean'),
    ('EE', u'Estonian'),
    ('EG', u'Egyptian'),
    ('ET', u'Ethiopian'),
    ('FI', u'Finnish'),
    ('FJ', u'Fijian'),
    ('FR', u'French'),
    ('GB', u'British'),
    ('GE', u'Georgian'),
    ('GH', u'Ghanaian'),
    ('GN', u'Guinean'),
    ('GR', u'Greek'),
    ('GY', u'Guyanese'),
    ('HK', u'Chinese'),
    ('HR', u'Croatian'),
    ('HU', u'Hungarian'),
    ('ID', u'Indonesian'),
    ('IE', u'Irish'),
    ('IN', u'Indian'),
    ('IQ', u'Iraqi'),
    ('IR', u'Iranian'),
    ('IS', u'Israeli'),
    ('IS', u'Icelander'),
    ('IT', u'Italian'),
    ('JM', u'Jamaican'),
    ('JO', u'Jordanian'),
    ('JP', u'Japanese'),
    ('KE', u'Kenyan'),
    ('KO', u'Korean'),
    ('KW', u'Kuwaiti'),
    ('KZ', u'Kazakhstani'),
    ('KZ', u'Kazakhstani'),
    ('LB', u'Lebanese'),
    ('LK', u'Lankan'),
    ('LT', u'Lithunian'),
    ('LU', u'Luxembourger'),
    ('MA', u'Moroccan'),
    ('MC', u'Monacan'),
    ('ME', u'Mexican'),
    ('MM', u'Mayanmarese'),
    ('MN', u'Mongolian'),
    ('MO', u'Macau'),
    ('MU', u'Mauritian'),
    ('MV', u'Maldivan'),
    ('MY', u'Malaysian'),
    ('NA', u'Namibian'),
    ('NG', u'Nigerian'),
    ('NL', u'Dutch'),
    ('NO', u'Norwegian'),
    ('NP', u'Nepalese'),
    ('NZ', u'Zealander'),
    ('OM', u'Omani'),
    ('PA', u'Panamanian'),
    ('PE', u'Peruvian'),
    ('PH', u'Filipino'),
    ('PK', u'Pakistani'),
    ('PO', u'Polish'),
    ('PT', u'Portugees'),
    ('PY', u'Paraguayan'),
    ('QA', u'Qatari'),
    ('RO', u'Romanian'),
    ('RU', u'Russian'),
    ('SA', u'Arabian'),
    ('SC', u'Seychellois'),
    ('SE', u'Swedish'),
    ('SG', u'Singaporean'),
    ('SK', u'Slovakian'),
    ('SN', u'Senegalese'),
    ('SO', u'Somali'),
    ('SP', u'Spanish'),
    ('TH', u'Thai'),
    ('TN', u'Tunisian'),
    ('TR', u'Turkish'),
    ('TW', u'Taiwanese'),
    ('TZ', u'Tanzanian'),
    ('UA', u'Ukrainian'),
    ('UG', u'Ugandan'),
    ('US', u'American'),
    ('UY', u'Uruguayan'),
    ('UZ', u'Uzbekistani'),
    ('VE', u'Venezuelan'),
    ('VN', u'Vietnamese'),
    ('YE', u'Yemeni'),
    ('ZA', u'African'),
    ('ZM', u'Zambian'),
    ('ZW', u'Zimbabwean'),
)

CURRENCY_ABBREVIATIONS = (
    ('AED', u'United Arab Emirates Dirham'),
    ('AFN', u'Afghanistan Afghani'),
    ('ALL', u'Albania Lek'),
    ('AMD', u'Armenia Dram'),
    ('ANG', u'Netherlands Antilles Guilder'),
    ('AOA', u'Angola Kwanza'),
    ('ARS', u'Argentina Peso'),
    ('AUD', u'Australia Dollar'),
    ('AWG', u'Aruba Guilder'),
    ('AZN', u'Azerbaijan New Manat'),
    ('BAM', u'Bosnia and Herzegovina Convertible Marka'),
    ('BBD', u'Barbados Dollar'),
    ('BDT', u'Bangladesh Taka'),
    ('BGN', u'Bulgaria Lev'),
    ('BHD', u'Bahrain Dinar'),
    ('BIF', u'Burundi Franc'),
    ('BMD', u'Bermuda Dollar'),
    ('BND', u'Brunei Darussalam Dollar'),
    ('BOB', u'Bolivia Boliviano'),
    ('BRL', u'Brazil Real'),
    ('BSD', u'Bahamas Dollar'),
    ('BTN', u'Bhutan Ngultrum'),
    ('BWP', u'Botswana Pula'),
    ('BYR', u'Belarus Ruble'),
    ('BZD', u'Belize Dollar'),
    ('CAD', u'Canada Dollar'),
    ('CDF', u'Congo/Kinshasa Franc'),
    ('CHF', u'Switzerland Franc'),
    ('CLP', u'Chile Peso'),
    ('CNY', u'China Yuan Renminbi'),
    ('COP', u'Colombia Peso'),
    ('CRC', u'Costa Rica Colon'),
    ('CUC', u'Cuba Convertible Peso'),
    ('CUP', u'Cuba Peso'),
    ('CVE', u'Cape Verde Escudo'),
    ('CZK', u'Czech Republic Koruna'),
    ('DJF', u'Djibouti Franc'),
    ('DKK', u'Denmark Krone'),
    ('DOP', u'Dominican Republic Peso'),
    ('DZD', u'Algeria Dinar'),
    ('EGP', u'Egypt Pound'),
    ('ERN', u'Eritrea Nakfa'),
    ('ETB', u'Ethiopia Birr'),
    ('EUR', u'Euro Member Countries'),
    ('FJD', u'Fiji Dollar'),
    ('FKP', u'Falkland Islands (Malvinas) Pound'),
    ('GBP', u'United Kingdom Pound'),
    ('GEL', u'Georgia Lari'),
    ('GGP', u'Guernsey Pound'),
    ('GHS', u'Ghana Cedi'),
    ('GIP', u'Gibraltar Pound'),
    ('GMD', u'Gambia Dalasi'),
    ('GNF', u'Guinea Franc'),
    ('GTQ', u'Guatemala Quetzal'),
    ('GYD', u'Guyana Dollar'),
    ('HKD', u'Hong Kong Dollar'),
    ('HNL', u'Honduras Lempira'),
    ('HRK', u'Croatia Kuna'),
    ('HTG', u'Haiti Gourde'),
    ('HUF', u'Hungary Forint'),
    ('IDR', u'Indonesia Rupiah'),
    ('ILS', u'Israel Shekel'),
    ('IMP', u'Isle of Man Pound'),
    ('INR', u'India Rupee'),
    ('IQD', u'Iraq Dinar'),
    ('IRR', u'Iran Rial'),
    ('ISK', u'Iceland Krona'),
    ('JEP', u'Jersey Pound'),
    ('JMD', u'Jamaica Dollar'),
    ('JOD', u'Jordan Dinar'),
    ('JPY', u'Japan Yen'),
    ('KES', u'Kenya Shilling'),
    ('KGS', u'Kyrgyzstan Som'),
    ('KHR', u'Cambodia Riel'),
    ('KMF', u'Comoros Franc'),
    ('KPW', u'Korea (North) Won'),
    ('KRW', u'Korea (South) Won'),
    ('KWD', u'Kuwait Dinar'),
    ('KYD', u'Cayman Islands Dollar'),
    ('KZT', u'Kazakhstan Tenge'),
    ('LAK', u'Laos Kip'),
    ('LBP', u'Lebanon Pound'),
    ('LKR', u'Sri Lanka Rupee'),
    ('LRD', u'Liberia Dollar'),
    ('LSL', u'Lesotho Loti'),
    ('LTL', u'Lithuania Litas'),
    ('LVL', u'Latvia Lat'),
    ('LYD', u'Libya Dinar'),
    ('MAD', u'Morocco Dirham'),
    ('MDL', u'Moldova Leu'),
    ('MGA', u'Madagascar Ariary'),
    ('MKD', u'Macedonia Denar'),
    ('MMK', u'Myanmar (Burma) Kyat'),
    ('MNT', u'Mongolia Tughrik'),
    ('MOP', u'Macau Pataca'),
    ('MRO', u'Mauritania Ouguiya'),
    ('MUR', u'Mauritius Rupee'),
    ('MVR', u'Maldives (Maldive Islands) Rufiyaa'),
    ('MWK', u'Malawi Kwacha'),
    ('MXN', u'Mexico Peso'),
    ('MYR', u'Malaysia Ringgit'),
    ('MZN', u'Mozambique Metical'),
    ('NAD', u'Namibia Dollar'),
    ('NGN', u'Nigeria Naira'),
    ('NIO', u'Nicaragua Cordoba'),
    ('NOK', u'Norway Krone'),
    ('NPR', u'Nepal Rupee'),
    ('NZD', u'New Zealand Dollar'),
    ('OMR', u'Oman Rial'),
    ('PAB', u'Panama Balboa'),
    ('PEN', u'Peru Nuevo Sol'),
    ('PGK', u'Papua New Guinea Kina'),
    ('PHP', u'Philippines Peso'),
    ('PKR', u'Pakistan Rupee'),
    ('PLN', u'Poland Zloty'),
    ('PYG', u'Paraguay Guarani'),
    ('QAR', u'Qatar Riyal'),
    ('RON', u'Romania New Leu'),
    ('RSD', u'Serbia Dinar'),
    ('RUB', u'Russia Ruble'),
    ('RWF', u'Rwanda Franc'),
    ('SAR', u'Saudi Arabia Riyal'),
    ('SBD', u'Solomon Islands Dollar'),
    ('SCR', u'Seychelles Rupee'),
    ('SDG', u'Sudan Pound'),
    ('SEK', u'Sweden Krona'),
    ('SGD', u'Singapore Dollar'),
    ('SHP', u'Saint Helena Pound'),
    ('SLL', u'Sierra Leone Leone'),
    ('SOS', u'Somalia Shilling'),
    ('SPL', u'Seborga Luigino'),
    ('SRD', u'Suriname Dollar'),
    ('STD', u'Sao Tome and Principe Dobra'),
    ('SVC', u'El Salvador Colon'),
    ('SYP', u'Syria Pound'),
    ('SZL', u'Swaziland Lilangeni'),
    ('THB', u'Thailand Baht'),
    ('TJS', u'Tajikistan Somoni'),
    ('TMT', u'Turkmenistan Manat'),
    ('TND', u'Tunisia Dinar'),
    ('TOP', u'Tonga Paanga'),
    ('TRY', u'Turkey Lira'),
    ('TTD', u'Trinidad and Tobago Dollar'),
    ('TVD', u'Tuvalu Dollar'),
    ('TWD', u'Taiwan New Dollar'),
    ('TZS', u'Tanzania Shilling'),
    ('UAH', u'Ukraine Hryvna'),
    ('UGX', u'Uganda Shilling'),
    ('USD', u'United States Dollar'),
    ('UYU', u'Uruguay Peso'),
    ('UZS', u'Uzbekistan Som'),
    ('VEF', u'Venezuela Bolivar'),
    ('VND', u'Viet Nam Dong'),
    ('VUV', u'Vanuatu Vatu'),
    ('WST', u'Samoa Tala'),
    ('XAF', u'Communaute Financiere Africaine (BEAC) CFA Franc BEAC'),
    ('XCD', u'East Caribbean Dollar'),
    ('XDR', u'International Monetary Fund (IMF) Special Drawing Rights'),
    ('XOF', u'Communaute Financiere Africaine (BCEAO) Franc'),
    ('XPF', u'Comptoirs Francais du Pacifique (CFP) Franc'),
    ('YER', u'Yemen Rial'),
    ('ZAR', u'South Africa Rand'),
    ('ZMW', u'Zambia Kwacha'),
    ('ZWD', u'Zimbabwe Dollar')
)

